### ISSUE TITLE
Ctrl-C throws an error when entry box is focused in IE

### ISSUE THREAD

**Issue by chromakode** [euphoria-io/heim#42]
First step: repro / collect more info on this; not getting exception error in sentry logs.

**Comment by ArkaneMoose** [comment]
I can reproduce consistently in IE 11.

This only occurs when text is highlighted in the input box.
IE 11 debugger indicates the problematic line is [line 11 in client/lib/ui/message-copy-formatter.js](https://github.com/euphoria-io/heim/blob/master/client/lib/ui/message-copy-formatter.js#L11).
The error thrown is an `IndexSizeError`.
It appears to have no error message.

![image](https://cloud.githubusercontent.com/assets/6319326/11022412/4a84691a-862c-11e5-828b-b0405ef7bb56.png)

When the error occurs, executing `uiwindow.getSelection()` in the console indicates that the `Selection`'s `rangeCount` is 0.

![image](https://cloud.githubusercontent.com/assets/6319326/11022432/db68f388-862c-11e5-9e79-4d853509cf4c.png)

I suspect that this is because a selection in a text input field is not counted as a range by IE's implementation of `window.getSelection()`.

Therefore, I think that the necessary fix is to add the following immediately before [line 11 in client/lib/ui/message-copy-formatter.js](https://github.com/euphoria-io/heim/blob/master/client/lib/ui/message-copy-formatter.js#L11):
```javascript
  if (selection.rangeCount === 0) {
    return
  }
```
